name: hawc
channels:
  - astropy
  - conda-forge
  - anaconda
dependencies:
  - python
  - numpy
  - matplotlib
  - astropy
  - scikit-image
  - scipy
  - setuptools
  - ipywidgets
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pip:
    - git+https://github.com/msgordon/liccy.git
